Workflow
martemoslet/social-media-client pull request #12
Opened 2023-01-26 14:31 UTC by martemoslet

2023-01-27 07:03 UTC, Fermain requested changes
There are some minor issues to be resolved but overall the quality of this PR is good. Tests are not all robust yet but the range of syntax and approaches is wide and there is clear engagement with the difficult concepts underlying testing.

I hope that I have made it clear what is an optional change and what is required, you would most likely pass with what you have here already but with a little extra work it can be elevated to a strong submission.

2023-01-27 07:03 UTC, Fermain commented on .github/workflows/static.yml
> +        uses: actions/checkout@v3
You should install and build the project too as extra steps here

2023-01-27 07:03 UTC, Fermain commented on cypress/e2e/login.cy.js
> +
I'm not sure about this test. I haven't run it yet myself just looking at the code it seems like you should enter the password first, then include {enter} when typing the email field?

2023-01-27 07:03 UTC, Fermain commented on src/js/api/auth/logout.test.js
> +    localStorage.setItem(profile, accessToken);
Please run a formatter on jest files to fix their indentation

2023-01-27 07:03 UTC, Fermain commented on src/js/api/posts/create.test.js
> +        expect(post).toMatchObject(mockpost);
You could also `expect(fetch).toHaveBeenCalled()` or similar

2023-01-27 07:03 UTC, Fermain commented on src/js/storage/save.test.js
> +    it("should save the correct value to localStorage", () => {
It would be nice to see this added to the logout test too

2023-01-27 07:03 UTC, Fermain commented on .eslintrc.json
> +            "files": ["**/*.test.js"],
I think you need to add your helper file here too

2023-01-27 11:26 UTC, martemoslet commented on .github/workflows/static.yml
> +        uses: actions/checkout@v3
Ok, I have made this change now

2023-01-27 11:47 UTC, martemoslet commented on cypress/e2e/login.cy.js
> +
I'm not sure what you mean here, do you mean that the expect should be after entering password and clicking enter?

2023-01-27 11:48 UTC, Fermain commented on cypress/e2e/login.cy.js
> +
No I mean that you should type the password first, then type the email then hit enter

2023-01-27 11:59 UTC, martemoslet commented on cypress/e2e/login.cy.js
> +
Thanks, got it. That works, and I have made that change

2023-01-27 12:14 UTC, martemoslet commented on src/js/api/auth/logout.test.js
> +    localStorage.setItem(profile, accessToken);
Do you mean running prettier or lint-staged over those files?

2023-01-27 12:21 UTC, martemoslet commented on .eslintrc.json
> +            "files": ["**/*.test.js"],
Ok, that is done

2023-01-27 12:48 UTC, martemoslet commented on src/js/storage/save.test.js
> +    it("should save the correct value to localStorage", () => {
Do you mean a new file like remove.test.js ? Or something like that in the logout test?

2023-01-27 12:50 UTC, Fermain commented on src/js/storage/save.test.js
> +    it("should save the correct value to localStorage", () => {
I mean this approach could be used to test logout

2023-01-27 12:50 UTC, Fermain commented on src/js/api/auth/logout.test.js
> +    localStorage.setItem(profile, accessToken);
Yeah or the built in formatter in vscode

2023-01-27 13:16 UTC, martemoslet commented on src/js/api/auth/logout.test.js
> +    localStorage.setItem(profile, accessToken);
Ok, thanks :) That is done

2023-01-27 13:17 UTC, martemoslet commented on src/js/storage/save.test.js
> +    it("should save the correct value to localStorage", () => {
Ok, I will try

2023-01-27 13:26 UTC, martemoslet commented on src/js/api/posts/create.test.js
> +        expect(post).toMatchObject(mockpost);
I have done some changes to this test now, not sure if it's exactly what you meant though

2023-01-27 14:19 UTC, martemoslet commented on src/js/storage/save.test.js
> +    it("should save the correct value to localStorage", () => {
I have updated this test now

2023-02-14 11:13 UTC, Fermain approved these changes
Thanks for implementing the feedback

2023-02-14 11:13 UTC, merged